apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: dev
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      volumes:
        - name: web-storage          # nama volume (internal, bebas)
          persistentVolumeClaim:
            claimName: web-app-pvc   # harus sama dengan nama PVC yang dibuat
      containers:
      - name: web-app
        image: nginx:1.25
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: web-storage        # harus sama dengan nama di volumes atas
            mountPath: /data         # lokasi mount di dalam container
        livenessProbe:          # kalau gagal → pod di-RESTART otomatis (deteksi pod hang/crash)
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10  # tunggu 10 detik sebelum mulai cek (kasih waktu app start)
          periodSeconds: 10        # cek setiap 10 detik
          failureThreshold: 3      # restart setelah 3x gagal berturut-turut
        readinessProbe:         # kalau gagal → pod KELUAR dari load balancer, tapi tidak di-restart
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5   # cek lebih cepat — deteksi kapan pod siap terima traffic
          periodSeconds: 5
          failureThreshold: 3      # keluarkan dari Service setelah 3x gagal
        env:
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: web-app-config
                key: APP_ENV
          - name: APP_PORT
            valueFrom:
              configMapKeyRef:
                name: web-app-config
                key: APP_PORT
          - name: APP_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: web-app-config
                key: APP_LOG_LEVEL
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: web-app-secret
                key: DB_PASSWORD
                optional: true
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: web-app-secret
                key: DB_USER
                optional: true
